language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
  
before_script:
  - "npm install --ignore-scripts"
  
script:
  - npm run build
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master